==> main-bs-512.log <==
┃  Job started at: 2022-11-14-022904 on thetagpu06           ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

The following have been reloaded with a version change:
  1) openmpi/openmpi-4.0.5 => openmpi/openmpi-4.1.4_ucx-1.12.1_gcc-9.4.0

Found venv at: /home/mbabeykoon/ai-science-training-series/07_largeScaleTraining/venv/, using that
./main.sh: line 132: /home/mbabeykoon/ai-science-training-series/07_largeScaleTraining/venvs/thetaGPU/2022-07-01/bin/activate: No such file or directory
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /home/mbabeykoon/.local/thetagpu/conda/2022-07-01/lib/python3.8/site-packages (22.3.1)

==> /home/mbabeykoon/ai-science-training-series/07_largeScaleTraining/src/ai4sci/logs/2022-11-14-012710-thetagpu06_ngpu1_ncpu256.log <==
[2022-11-14 01:38:45,215][ai4sci.trainer][INFO] - [0] [0/1: 128000 / 1281167 (10%)] epoch=0.0000 dt=0.5695 running_loss=0.0009 batch_loss=0.0081 acc=0.0095 batch_acc=0.1113
[2022-11-14 01:39:09,877][ai4sci.trainer][INFO] - [0] [0/1: 133120 / 1281167 (10%)] epoch=0.0000 dt=0.6458 running_loss=0.0009 batch_loss=0.0080 acc=0.0100 batch_acc=0.1621
[2022-11-14 01:39:41,549][ai4sci.trainer][INFO] - [0] [0/1: 138240 / 1281167 (11%)] epoch=0.0000 dt=0.9984 running_loss=0.0009 batch_loss=0.0078 acc=0.0107 batch_acc=0.1406
[2022-11-14 01:40:06,935][ai4sci.trainer][INFO] - [0] [0/1: 143360 / 1281167 (11%)] epoch=0.0000 dt=0.7455 running_loss=0.0010 batch_loss=0.0082 acc=0.0112 batch_acc=0.1133
[2022-11-14 01:40:38,967][ai4sci.trainer][INFO] - [0] [0/1: 148480 / 1281167 (12%)] epoch=0.0000 dt=0.9039 running_loss=0.0010 batch_loss=0.0077 acc=0.0118 batch_acc=0.1465
[2022-11-14 01:41:04,163][ai4sci.trainer][INFO] - [0] [0/1: 153600 / 1281167 (12%)] epoch=0.0000 dt=0.9565 running_loss=0.0010 batch_loss=0.0079 acc=0.0123 batch_acc=0.1504
[2022-11-14 01:41:36,353][ai4sci.trainer][INFO] - [0] [0/1: 158720 / 1281167 (12%)] epoch=0.0000 dt=0.8108 running_loss=0.0011 batch_loss=0.0080 acc=0.0129 batch_acc=0.1504
[2022-11-14 01:42:02,176][ai4sci.trainer][INFO] - [0] [0/1: 163840 / 1281167 (13%)] epoch=0.0000 dt=0.8976 running_loss=0.0011 batch_loss=0.0078 acc=0.0136 batch_acc=0.1543
[2022-11-14 01:42:33,687][ai4sci.trainer][INFO] - [0] [0/1: 168960 / 1281167 (13%)] epoch=0.0000 dt=0.8501 running_loss=0.0011 batch_loss=0.0076 acc=0.0142 batch_acc=0.1816
[2022-11-14 01:42:58,868][ai4sci.trainer][INFO] - [0] [0/1: 174080 / 1281167 (14%)] epoch=0.0000 dt=1.0651 running_loss=0.0012 batch_loss=0.0076 acc=0.0148 batch_acc=0.1855

==> main-bs-512.log <==
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/mbabeykoon/ai-science-training-series/07_largeScaleTraining
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: ai4sci
  Building editable for ai4sci (pyproject.toml): started
  Building editable for ai4sci (pyproject.toml): finished with status 'done'
  Created wheel for ai4sci: filename=ai4sci-0.0.0-0.editable-py3-none-any.whl size=1171 sha256=997a0c8fc04f3272d69333d4bb130eec0be9999100d856a84d578facdddc76cc
  Stored in directory: /tmp/pip-ephem-wheel-cache-t18v7ig6/wheels/10/f7/26/0607117a994e7f502fb96e170505db1d4f0d1ee4e848c08f25
Successfully built ai4sci
Installing collected packages: ai4sci
  Attempting uninstall: ai4sci
    Found existing installation: ai4sci 0.0.0
    Uninstalling ai4sci-0.0.0:
      Successfully uninstalled ai4sci-0.0.0
Successfully installed ai4sci-0.0.0
WIDTH:
DIR=/home/mbabeykoon/ai-science-training-series/07_largeScaleTraining/src/ai4sci
MAIN=/home/mbabeykoon/ai-science-training-series/07_largeScaleTraining/src/ai4sci/main.py
PARENT=/home/mbabeykoon/ai-science-training-series/07_largeScaleTraining/src
ROOT=/home/mbabeykoon/ai-science-training-series/07_largeScaleTraining
LOGDIR=/home/mbabeykoon/ai-science-training-series/07_largeScaleTraining/src/ai4sci/logs
LOGFILE=/home/mbabeykoon/ai-science-training-series/07_largeScaleTraining/src/ai4sci/logs/2022-11-14-022904-thetagpu06_ngpu1_ncpu256.log
IBV_FORK_SAFE=
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  STARTING A NEW RUN ON 1 GPUs 256  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┃  - DATE: 2022-11-14-022904
┃  - NCPUS: 256
┃  - NRANKS: 1
┃  - NGPUS PER RANK: 1
┃  - NGPUS TOTAL: 1
┃  - MAIN: /home/mbabeykoon/ai-science-training-series/07_largeScaleTraining/src/ai4sci/main.py
┃  - Writing logs to /home/mbabeykoon/ai-science-training-series/07_largeScaleTraining/src/ai4sci/logs/2022-11-14-022904-thetagpu06_ngpu1_ncpu256.log
┃  - python3: /lus/theta-fs0/software/thetagpu/conda/2022-07-01/mconda3/bin/python3
┃  - mpirun: /lus/theta-fs0/software/thetagpu/openmpi/openmpi-4.1.4_ucx-1.12.1_gcc-9.4.0/bin/mpirun
┃  - ai4sci: /home/mbabeykoon/ai-science-training-series/07_largeScaleTraining/src/ai4sci/__init__.py
┃  - exec: /lus/theta-fs0/software/thetagpu/openmpi/openmpi-4.1.4_ucx-1.12.1_gcc-9.4.0/bin/mpirun --verbose     -n 1     --hostfile /var/tmp/cobalt.10114915     -npernode 1     -x PYTHONUSERBASE     -x PYTHONSTARTUP     -x http_proxy     -x https_proxy     -x PATH     -x LD_LIBRARY_PATH /lus/theta-fs0/software/thetagpu/conda/2022-07-01/mconda3/bin/python3 /home/mbabeykoon/ai-science-training-series/07_largeScaleTraining/src/ai4sci/main.py batch_size=512
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

[thetagpu06:4095358] Warning: could not find environment variable "PYTHONSTARTUP"
2022-11-14 02:29:27.465056: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:690] Error in PredictCost() for the op: op: "CropAndResize" attr { key: "T" value { type: DT_UINT8 } } attr { key: "extrapolation_value" value { f: 0 } } attr { key: "method" value { s: "bilinear" } } inputs { dtype: DT_UINT8 shape { dim { size: 1 } dim { size: -5 } dim { size: -6 } dim { size: 3 } } } inputs { dtype: DT_FLOAT shape { dim { size: -2 } dim { size: 4 } } } inputs { dtype: DT_INT32 shape { dim { size: -2 } } } inputs { dtype: DT_INT32 shape { dim { size: 2 } } } device { type: "CPU" vendor: "AuthenticAMD" model: "241" frequency: 2245 num_cores: 2 environment { key: "cpu_instruction_set" value: "SSE, SSE2, SSE3" } environment { key: "eigen" value: "3.4.90" } l1_cache_size: 32768 l2_cache_size: 524288 l3_cache_size: 268435456 memory_size: 268435456 } outputs { dtype: DT_FLOAT shape { dim { size: -2 } dim { size: -10 } dim { size: -11 } dim { size: 3 } } }
client_loop: send disconnect: Connection reset